In [5]:
import numpy as np
import time
np.random.seed(42)
print("Numpy version: ",  np.__version__)

Numpy version:  2.4.6


In [9]:
prices = list(range(1, 1_000_001))

# Loop version
start = time.time()
discounted_loop = [p * 0.95 for p in prices]
loop_time = time.time() - start  # Fixed typo here
print(f"Loop version: {loop_time:.4f} seconds")

# Vectorized Numpy version
prices_np = np.array(prices)  # Added this missing initialization
start = time.time()
discounted_np = prices_np * 0.95
np_time = time.time() - start
print(f"Numpy version: {np_time:.4f} seconds")

print(f"NumPy was about {loop_time / np_time:.0f}x faster")


Loop version: 0.0636 seconds
Numpy version: 0.0020 seconds
NumPy was about 32x faster


In [14]:
a = np.array([10, 20, 30, 80])

zeros = np.zeros((2, 3))
ones = np.ones((3, 3))


seq = np.arange(0, 30, 2)

lin = np.linspace(0, 1, 5)

print("a: ", a)
print("Zeros: ", zeros)  
print("Ones: ", ones)
print("seq: ", seq)      
print("lin: ", lin)

a:  [10 20 30 80]
Zeros:  [[0. 0. 0.]
 [0. 0. 0.]]
Ones:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
seq:  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
lin:  [0.   0.25 0.5  0.75 1.  ]


In [4]:
import pandas as pd
data = {
    "name" : ["Ali", "Khan" , "Hussain" ],
    "Age": [21,24,21],
    "major":  ["CS","AI","Stats"],
    "Gender": ["M","F","M"]
}
df =pd.DataFrame(data)
print(df)

      name  Age  major Gender
0      Ali   21     CS      M
1     Khan   24     AI      F
2  Hussain   21  Stats      M


IndentationError: expected an indented block after function definition on line 1 (1335877800.py, line 3)